hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  job_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  env: {}
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra: []
    task:
    - train=glob(*)
  job:
    name: train
    override_dirname: train=glob(*)
    id: ???
    num: ???
    config_name: main
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.1.1
    cwd: /Users/dfomin/projects/7wd-bot/swd_bot/train
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/dfomin/projects/7wd-bot/swd_bot/train/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    choices:
      train: train_flat
      train/data_provider@train.valid_data_loader: torch_valid
      train/data_provider@train.train_data_loader: torch_train
      train/feature_extractor: flat_feature_extractor
      train/model: torch_baseline_flat
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: disabled
      hydra/hydra_logging: disabled
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
train:
  model:
    _target_: swd_bot.model.torch_models.TorchBaseline
  feature_extractor:
    _target_: swd_bot.data_providers.feature_extractor.FlattenFeatureExtractor
  train_data_loader:
    _target_: swd_bot.data_providers.torch_data_provider.TorchDataLoader
    states_path: ../../datasets/buy_discard_build/states_train.pkl
    actions_path: ../../datasets/buy_discard_build/actions_train.pkl
    batch_size: 256
    shuffle: true
  valid_data_loader:
    _target_: swd_bot.data_providers.torch_data_provider.TorchDataLoader
    states_path: ../../datasets/buy_discard_build/states_valid.pkl
    actions_path: ../../datasets/buy_discard_build/actions_valid.pkl
    batch_size: 256
    shuffle: false
  epochs: 30
  device: cpu
  output_path: ../../models
  model_prefix: model_flat
