_target_: swd_bot.data_providers.torch_data_provider.TorchDataProvider
train:
  states_path: "../../datasets/buy_discard_build/states_train.pkl"
  actions_path: "../../datasets/buy_discard_build/actions_train.pkl"
  batch_size: 256
  shuffle: true
valid:
  states_path: "../../datasets/buy_discard_build/states_valid.pkl"
  actions_path: "../../datasets/buy_discard_build/actions_valid.pkl"
  batch_size: 256
  shuffle: false
test:
  states_path: "../../datasets/buy_discard_build/states_test.pkl"
  actions_path: "../../datasets/buy_discard_build/actions_test.pkl"
  batch_size: 256
  shuffle: false
defaults:
  - feature_extractor: flat