epochs: 30
device: cpu
output_path: ../../models
model_prefix: model_c2v_v2
defaults:
  - model: torch_baseline_flat_v2
  - feature_extractor: card2vec_feature_extractor
  - data_provider@train_data_loader: card2vec_train
  - data_provider@valid_data_loader: card2vec_valid