epochs: 30
device: cpu
output_path: ../../models
model_prefix: model_emb_v2
defaults:
  - model: torch_baseline_emb_v2
  - feature_extractor: emb_feature_extractor
  - data_provider@train_data_loader: torch_train
  - data_provider@valid_data_loader: torch_valid